bindkey -e
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

HISTSIZE=20000
SAVEHIST=20000

source ${ZDOTDIR:-~}/.antidote/antidote.zsh
antidote load

if [ -d "/opt/homebrew/bin" ]; then
  export PATH="/opt/homebrew/bin:$PATH"
fi

if [ -x "$HOME/.pyenv/bin/pyenv" ]; then
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  # eval "$(pyenv init -)"
  # eval "$(pyenv virtualenv-init -)"
fi


if [ -d "$HOME/.cargo" ]; then
  export CARGO_BIN="$HOME/.cargo/bin"
  export PATH="$CARGO_BIN:$PATH"
fi

if [ -d "/usr/local/go/bin" ]; then
  export GOROOT=/usr/local/go
  export GOPATH=$HOME/go
  export PATH=$GOPATH/bin:$PATH:$GOROOT/bin
fi

export PATH=$PATH:/usr/local/bin
export PATH=$HOME/.local/bin:$PATH

if [ -d "$HOME/usr/bin" ]; then
  export USER_BIN="$HOME/usr/bin"
  export PATH=$USER_BIN:$PATH
fi

if command -v nvim > /dev/null ; then
  export EDITOR=nvim
  export VISUAL=nvim
  alias vim="nvim"
elif command -v vim > /dev/null ; then
  export EDITOR=vim
  export VISUAL=vim
fi

bindkey -e

if [ -d  "$HOME/.asdf" ]; then
  . "$HOME/.asdf/asdf.sh"
  fpath=(${ASDF_DIR}/completions $fpath)
  # . "$HOME/.asdf/completions/asdf.bash"
fi
source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"

# eval "$(starship init zsh)"

autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit
if [[ ! ~/.zcompdump.zwc -nt ~/.zcompdump ]]; then
  zcompile -R -- ~/.zcompdump.zwc ~/.zcompdump
fi
[ -x /usr/local/bin/aws_completer ] && complete -C '/usr/local/bin/aws_completer' aws
command -v zoxide > /dev/null && eval "$(zoxide init zsh)"

autoload -Uz promptinit && promptinit && prompt powerlevel10k
# autoload -Uz promptinit && promptinit

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

if [ -f $HOME/.rsyncignore ]; then
  alias rsynci="rsync --exclude-from $HOME/.rsyncignore"
fi

if command -v eza > /dev/null ; then
  alias l="eza -la"
  alias lt="eza -la -t modified -r"
  alias li="eza -la --git-ignore"
  alias lit="eza -la --git-ignore -t modified -r"
fi
alias kssh="kitty +kitten ssh"

display_colors ()
{
  for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done
}

newenv ()
{
  echo "export VIRTUAL_ENV=$PWD/.venv\nexport PATH=$PWD/.venv/bin:\$PATH" > .envrc
}
